### PR TITLE
feat(chrome): Add typescriptreact and javascriptreact debug support

### PR DESCRIPTION
**Pull request by kozer**
vscode-chrome-debug

### CODE REVIEW

**Comment by Pocco81** [comment]
By any chance, did you test it already?

**Comment by kozer** [comment]
Yes I did. It worked as expected.

**Comment by kozer** [comment]
Just checked that and I had a bug. Fixed.

**Comment by Pocco81** [comment]
> Can I send you a pm somehow?

Yes but considering that you want to discuss about the codebase and a debugger for Haskell, then why not open an issue instead?

> The only thing I didn't test is the uninstall part

Don't worry about that, I looked at the script and it seemed fine.

**Comment by Pocco81** [comment]
Thanks for the PR btw :+1:

**Pull request merged**
